apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
  labels:
    app: python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app-container
        image: kanchanpal9/python-app:latest  # ✅ Replace with your actual Docker Hub image if needed
        ports:
        - containerPort: 5000
